symfonycasts_reset_password:
    request_password_repository: App\Infrastructure\User\Repository\ResetPasswordRequestRepository

    # The length of time in seconds that a password reset request is valid for after it is created.
    lifetime: 86_400 # 24h (60 * 60 * 24)

    # Another password reset cannot be made faster than this throttle time in seconds.
    throttle_limit: 60 # 1m
