twig:
    default_path: '%kernel.project_dir%/templates'

when@dev:
    twig:
        globals:
            GRAPHIQL_JWT_TOKEN: '%env(GRAPHIQL_JWT_TOKEN)%'

when@test:
    twig:
        strict_variables: true
